version: '3.7'

services:

  elasticsearch:
    environment: 
      - ES_JAVA_OPTS=-Xms500m -Xmx500m
    volumes:
      - ch07-es-data:C:\data

  reverse-proxy:
    command: --docker --docker.endpoint=npipe:////./pipe/docker_engine --api
    ports:
      - "80"
      - "8080"
    volumes:
      - type: npipe
        source: \\.\pipe\docker_engine
        target: \\.\pipe\docker_engine

  nerd-dinner-db:
    volumes:
      - ch07-db-data:C:\data

  kibana:
    depends_on:
      - elasticsearch
    labels:
      - "traefik.frontend.rule=Host:kibana.nerddinner.local"

  nerd-dinner-save-handler:
    depends_on:
      - nerd-dinner-db
      - message-queue

  nerd-dinner-index-handler:
    depends_on:
      - elasticsearch
      - message-queue

  nerd-dinner-api:
    depends_on:
      - nerd-dinner-db
    labels:
      - "traefik.frontend.rule=Host:api.nerddinner.local"

  nerd-dinner-homepage:
    labels:
      - "traefik.frontend.rule=Host:nerddinner.local;Path:/,/css/site.css"
      - "traefik.frontend.priority=10"

  nerd-dinner-web:
    environment: 
      - HomePage:Enabled=false
      - DinnerApi:Enabled=true
    env_file:
      - api-keys.env
    depends_on:
      - nerd-dinner-db
      - message-queue
    labels:
      - "traefik.frontend.rule=Host:nerddinner.local;PathPrefix:/"
      - "traefik.frontend.priority=1"     

networks:
  nd-net:
    external:
      name: nat

volumes:
  ch07-es-data:
  ch07-db-data: