version: '3.7'

services:
  webapi:
    image: dockeronwindows/ch11-webapi-vscode:2e
    build:
      context: .
      args: 
        CONFIGURATION: Release
    networks:
      - app-net

networks:
  app-net: